league_oauth2_server:
    authorization_server:
        private_key: '%kernel.project_dir%/var/keys/private.key'
        private_key_passphrase: null
        encryption_key: 'Ex4Q6Ik/9y+tH/ujvWEQDYDX6xBFqkwLVfcU9kADVng='
        encryption_key_type:  plain # One of "plain"; "defuse"
        access_token_ttl: P1W
        refresh_token_ttl: P1M
        auth_code_ttl: PT10M
        enable_client_credentials_grant: true
        enable_password_grant: true
        enable_refresh_token_grant: true
        enable_auth_code_grant: true
        require_code_challenge_for_public_clients: true
        persist_access_token: true

    resource_server:
        public_key: '%kernel.project_dir%/var/keys/public.key'

    scopes:
        available: '%oauth2_client_available_scopes%'
        default: ['email']

    persistence:
        doctrine:
            entity_manager: default

    role_prefix:          ROLE_OAUTH2_

    client:
        classname:        App\Entity\OAuth2\Client
