tasks:
  - name: start
    init: |
      docker-compose up -d
      composer install
      bin/console doctrine:migrations:migrate -n
      wget https://get.symfony.com/cli/installer -O - | bash
      /home/gitpod/.symfony5/bin/symfony server:ca:install
      /home/gitpod/.symfony5/bin/symfony server:start -d
    command: yarn encore dev-server


