tasks:
  - name: start
    before: |
      docker-compose up -d
      composer install
      yarn install
      bin/console doctrine:migrations:migrate -n
      wget https://get.symfony.com/cli/installer -O - | bash
      /home/gitpod/.symfony5/bin/symfony server:ca:install
    command: /home/gitpod/.symfony5/bin/symfony server:start -d && yarn encore dev-server


